"""add audit_log, knowledge_article, incident_knowledge models

Revision ID: 073fa660bb31
Revises: a99e49bbe0ae
Create Date: 2026-08-12 19:46:15.778868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073fa660bb31'
down_revision = 'a99e49bbe0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_articles', schema=None) as batch_op:
        batch_op.create_index('idx_article_created', ['created_at'], unique=False)
        batch_op.create_index('idx_article_title', ['title'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=100), nullable=False),
    sa.Column('field_changed', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_field', ['field_changed'], unique=False)
        batch_op.create_index('idx_audit_incident', ['incident_id'], unique=False)
        batch_op.create_index('idx_audit_timestamp', ['timestamp'], unique=False)

    op.create_table('incident_knowledge',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['knowledge_article_id'], ['knowledge_articles.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'knowledge_article_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_knowledge')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_timestamp')
        batch_op.drop_index('idx_audit_incident')
        batch_op.drop_index('idx_audit_field')

    op.drop_table('audit_logs')
    with op.batch_alter_table('knowledge_articles', schema=None) as batch_op:
        batch_op.drop_index('idx_article_title')
        batch_op.drop_index('idx_article_created')

    op.drop_table('knowledge_articles')
    # ### end Alembic commands ###
