"""add resolved_at to incidents

Revision ID: 0e26ff0049e8
Revises: 97d9208eb700
Create Date: 2026-08-13 01:53:08.753440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e26ff0049e8'
down_revision = '97d9208eb700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_incidents_resolved_at'), ['resolved_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_resolved_at'))
        batch_op.drop_column('resolved_at')

    # ### end Alembic commands ###
