"""add incident model

Revision ID: a99e49bbe0ae
Revises: 7a6c3b21693b
Create Date: 2026-08-12 18:54:16.527123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99e49bbe0ae'
down_revision = '7a6c3b21693b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_priority_text', sa.String(length=255), nullable=True),
    sa.Column('impact', sa.String(length=20), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolve_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_hold_minutes', sa.Integer(), nullable=False),
    sa.Column('hold_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_code', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('assigned_priority_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("impact IN ('low', 'medium', 'high')", name='valid_impact'),
    sa.CheckConstraint("resolution_code IS NULL OR resolution_code IN ('fixed', 'workaround', 'not_a_bug', 'duplicate', 'cant_reproduce', 'third_party')", name='valid_resolution_code'),
    sa.CheckConstraint("status IN ('new', 'triage', 'assigned', 'in_progress', 'on_hold', 'resolved', 'reopened', 'closed')", name='valid_status'),
    sa.CheckConstraint("urgency IN ('low', 'medium', 'high')", name='valid_urgency'),
    sa.CheckConstraint('(assigned_priority_id IS NOT NULL AND response_due IS NOT NULL AND resolve_due IS NOT NULL) OR assigned_priority_id IS NULL', name='sla_requires_priority'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['assigned_priority_id'], ['priorities.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_created_at'))
        batch_op.drop_index(batch_op.f('ix_incidents_assignee_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_application_id'))

    op.drop_table('incidents')
    # ### end Alembic commands ###
