"""make impact and urgency nullable for triage flow

Revision ID: de6cd683615b
Revises: 073fa660bb31
Create Date: 2026-08-12 20:46:47.309766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6cd683615b'
down_revision = '073fa660bb31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column('impact',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('urgency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column('urgency',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('impact',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
